### ISSUE TITLE
Clarify / fix build process

### ISSUE THREAD

**Issue by btholt** [xgrommx/rx-book#10]
Hi! Super excited to read through this content. I'm trying to build this locally so I can read it on a long plane ride. It seems the build process isn't quite working. When trying to run the `default` or `publish` tasks, Grunt cannot find the `gitbooks` task. When trying to run the `build` task, Grunt cannot find `normalize.less`. It may also be helpful to give a step-by-step in the README.md of how to build the project.

Thanks again!

**Comment by xgrommx** [comment]
Of course I know about it. In a early version of gitbook I had some problems with grunt tasks. I need fix it. Now I build my book so:

1) ```npm -g i gitbook grunt-cli```
2) ```in folder with book npm install```
3) ```gitbook build or serve``` (if you wish live reload after changes)
4) ```grunt gh-pages``` - build book for public

I know it is no good idea, but I don't have time for fix it. Also I change theme and put in local with a book and you should after all commands which I described above run ```grunt build``` command.

I hope this description help you. Thanks.
