### ISSUE TITLE
Rx.spawn doesn't work

### ISSUE THREAD

**Issue by tyrchen** [xgrommx/rx-book#22]
In chapter http://xgrommx.github.io/rx-book/content/getting_started_with_rxjs/creating_and_querying_observable_sequences/generators_and_observable_sequences.html, ``Rx.spawn`` doesn't work.

**Comment by xgrommx** [comment]
@tyrchen I know about it because I proposed some changes and improvements to `Rx.Observable.spawn`

**Comment by xgrommx** [comment]
@tyrchen has been fixed! Cheers :beer:
