### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by morenoh149** [xgrommx/rx-book#5]
http://xgrommx.github.io/rx-book/content/guidelines/..%5C../content/guidelines/introduction/README.html 404s
http://xgrommx.github.io/rx-book/content/guidelines/when/..%5C..%5C../content/guidelines/contract/README.html
http://xgrommx.github.io/rx-book/content/guidelines/when/..%5C..%5C../content/guidelines/using/README.html
http://xgrommx.github.io/rx-book/content/guidelines/when/..%5C..%5C../content/guidelines/implementations/README.html

great book btw

**Comment by hansgru** [comment]
+1 Please fix the broken links. They're too many, and after some chapter the docs are practically useless.

**Comment by cvuorinen** [comment]
Almost all of the TOC links give 404 currently, because the URL paths have backslashes instead of forward slashes.
