### ISSUE TITLE
pdf or epub version

### ISSUE THREAD

**Issue by ppoliani** [xgrommx/rx-book#9]
It would be nice if there was a alternative digital version of the book

**Comment by hansgru** [comment]
it would be nice if the online version wouldn't have broken links inside in first place. 
If the links would be correct, there are tons of tools and free online services that can generate out of a set of **correct** HTML files an Epub or a PDF one.

**Comment by pavlospolianidis** [comment]
@hansgru why make things difficult. Why not add a grunt task that creates it automatically.

**Comment by hansgru** [comment]
@pavlospolianidis 
It's not difficult - the **base** must be correct in first place. Than you can convert it to whatever format or with whatever tool you like (with grunt or not) -  that's the trivial part.

The main problem with the documentation is that the navigation is JS based and is broken - completely. So other formats won't help here. (see the other issues regarding this problem).

**Comment by xgrommx** [comment]
@ppoliani Yes, I would be made a pdf version in future. But now I have one urgent issue regarding visualization stream of data.

**Comment by xgrommx** [comment]
@ppoliani I was created pdf version of rx-book https://github.com/xgrommx/rx-book-pdf
